export enum MessageResponse {
    USER_NOT_FOUND = 'User not found!',
    USER_EXISTED = 'Username or email existed!',
    WRONG_USERNAME_OR_PASSWORD = 'Username or password is not correct',
    CREATE_USER_SUCCESS = 'Created user successfully!',
    ROLE_NOT_FOUND = 'Role Not Found!',
    INTERNAL_SERVER_ERROR = 'Internal Server Error! Please try again',
    CREATE_USER_FAILED = 'Failed to create user',
    LOGIN_FAILED = 'Failed to login',
    LOGIN_SUCCESS = 'Login successfully!',
    REQUEST_FAILED = 'Request failed!',
    UNAUTHORIZED = 'User not authorized!',
    FORBIDDEN = 'Forbidden: Insufficient permissions',
    GET_TYPES_ERROR = 'Cannot get the resource types',
    GET_TYPE_SUCCESS = 'Get the resource types successfully',
    RESOURCE_TYPE_NOT_FOUND = 'Resource type not found!',
    CREATE_RESOURCE_FAILED = 'Create resource failed!',
    CREATE_RESOURCE_SUCCESS = 'Resource created successfully!',
    FILTER_RESOURCE_FAILED = 'Filter the resources failed!',
    FILTER_RESOURCE_SUCCESS = 'Filter the resources successfully!',
    RESOURCE_NOT_FOUND = 'Resource not found!',
    GET_RESOURCE_DETAILS_FAILED = 'Cannot get the resource details!',
    GET_RESOURCE_DETAILS_SUCCESS = 'Get the resource details successfully!',
    UPDATE_RESOURCE_SUCCESS = 'Resource details updated successfully!',
    UPDATE_RESOURCE_FAILED = 'Resource details updated failed!',
    DELETE_RESOURCE_FAILED = 'Resource deleted failed!',
    DELETE_RESOURCE_SUCCESS = 'Resource deleted successfully!'
}